### ISSUE TITLE
how to broadcast transaction

### ISSUE THREAD

**Issue by nbit99** [Bitrue-exchange/libada-go#2]
`
		tx := NewTx()
		tx.AddInputs(MustInput("2558aad25ec6b0e74009f36dc60d7fec6602ce43d603e80c9edde9dd54c78eb4", 0))
		tx.AddOutputs(NewOutput(shellAddress, 9000000)).SetFee(1000000).SetInvalidAfter(832163)
		tx.AddKeyWitness(NewKeysWitness(rootpub, rootprv.Sign(tx.Hash())))

		fmt.Println(hex.EncodeToString(tx.Bytes()))
`
how to broadcast the hex?
rosetta and cardano wallet api (http://192.168.2.132:8090/v2/proxy/transactions) can't broadcast the hex

**Comment by lsdbitrue** [comment]
you can use [cardano-graphql](https://github.com/input-output-hk/cardano-graphql).

and here is an example

```graphql
mutation SendRawTx($rawtx: String!) {
	submitTransaction(transaction: $rawtx) {
	  hash
	}
  }
```
